UMC-7-FIT-PASS/fitpass-web

src/components/Header.tsx

- 헤더가 고정이 안 돼서 z-50 속성 추가했습니다!

style: Header.tsx에 z-50 추가

---

public/svg/arrow_drop_down.svg
public/svg/arrow_drop_up.svg
src/assets/svg/ArrowDropDown.tsx
src/assets/svg/ArrowDropUp.tsx
src/assets/svg/index.ts
src/components/FitnessCard.tsx
src/index.css
src/pages/ExploreFitness.tsx
src/pages/ExploreFitness/CategorySlide.tsx
src/pages/ExploreFitness/Dropdown.tsx
src/pages/ExploreFitness/ExploreFitness.tsx
src/pages/Home/CardCol.tsx
src/pages/Home/Home.tsx
src/pages/index.ts

- close #3 
- 피트니스 시설 살펴보기 페이지 구현
- 공통 컴포넌트(피트니스 카드) 구현

[Feature] 피트니스 시설 살펴보기 페이지 구현

---

src/pages/SearchFitness.tsx
src/type/fitnessCard.ts

#38 
- close #1
- 피트니스 검색 헤더에 검색어를 입력하면 해당 키워드가 들어간 시설 목록 표시

[Feature] 시설 검색 구현

---

src/components/Header.tsx
src/components/paymentCard/PaymentCard.tsx
src/components/paymentCard/Toggle.tsx
src/components/setLocation/SetLocationOption.tsx
src/pages/PayHistory.tsx
src/pages/index.ts
src/routes/Router.tsx

#54 
- 구매 내역 페이지 라우터 추가
- 구매 내역 페이지 헤더를 메인 헤더로 추가
- 목록 필터링 토글 구현
- 필터 토글에 따른 목록 표시 구현

[Feature] 구매 내역 화면 구현

---

package.json
src/apis/searchFitness.ts
src/components/FitnessCard.tsx
src/hooks/useGetSearchFitness.ts
src/pages/GuideLogin.tsx
src/pages/SearchFitness.tsx
src/type/searchFitness.ts
yarn.lock

#49 
- 시설 검색 api 연결
- 검색 디바운싱 적용
- 무한 스크롤 구현
백엔드 토큰 관련 오류가 주기적으로 발생합니다.

[Feature] 시설 검색 api 연결

---

src/apis/axios-instance.ts
src/context/AuthContext.tsx
src/hooks/useSignin.ts

[fix] 헤더에 토큰 추가

---

src/apis/payHistory.ts
src/components/paymentCard/PaymentCard.tsx
src/components/paymentCard/SkeletonPaymentCard.tsx
src/hooks/useGetPayHistory.ts
src/pages/PayHistory.tsx
src/type/payHistory.ts

#56 
- 전체 목록 연결
- 요금제 목록 연결
- 코인 목록 연결
- isSubscribing에 따른 '정기 구독 해지하기' 버튼 추가
- 로딩시 스켈레톤 ui 추가
- 무한 스크롤 구현

[Feat] 구매 내역 및 구독 해지 api 연결

---

src/components/setLocation/GetCurrentLocation.tsx
src/pages/SearchLocation.tsx

- close #45 
- isLogin이 false일 경우 로그인 유도 화면이 표시되도록 변경했습니다.

feat: 비로그인 시 로그인 유도 화면 표시되도록 변경

---

src/apis/buyCoin.ts
src/apis/subscibe.ts
src/hooks/usePostPayCoin.ts
src/hooks/usePostPlan.ts
src/pages/Payment.tsx
src/types/buyCoin.ts

#73 
- 플랜 구독 유형에 따른 결제 요청
- 요청 성공시 백엔드에 요청

[Feature] 플랜 구독 api 연결

---

src/pages/FitnessDetails/ReviewList.tsx

fix: maps typeError 해결을 위한 수정

---

src/pages/admin/AdminDashboard.tsx
src/pages/admin/AdminUser.tsx

- close #99 
- 어드민 대시보드, 사용자 화면 표 길이 수정
- 대시보드 화면 페이지네이션 추가

[feat] 어드민 대시보드, 사용자 화면 표 길이 수정

---

src/hooks/useSignin.ts
src/hooks/useSocialSignup.ts

- close #103 
-  로그인시 어드민 계정 navigate 경로 분리

[feat] 어드민 계정 navigate 경로 수정

---

src/pages/admin/AdminSubscibe.tsx

#94 
- 구독 상품 테이블 구현
- 저장 버튼 및 모달 구현
추후 api 연결

feat: 어드민 구독 상품 관리 화면 구현

---

src/pages/admin/AdminCoin.tsx
src/pages/admin/AdminSubscribe.tsx
src/pages/index.ts

- close #95 
- 어드민 코인 상품 관리 UI구현

[Feature] 어드민 코인 상품 관리 UI 구현

---

src/pages/Signin/InputField.tsx
src/pages/Signin/Signin.tsx

[feat] 로그인 아이콘 크기 지정

---

src/apis/config.ts
src/hooks/useDebounce.ts
src/pages/admin/AdminDashboard.tsx
src/pages/admin/AdminSignin.tsx
src/pages/admin/AdminUser.tsx

- close #112 
- 어드민 사용자 목록 화면 api 연결
- 검색 기능 useDebounce 훅 파일  생성
- 어드민 로그인 api 연결

[Feat] 어드민 사용자 목록 화면 api 연결

---

src/apis/adminPayHistory/adminPayHistory.ts
src/components/Pagination.tsx
src/hooks/useGetAdminPayHistory.ts
src/index.css
src/pages/admin/AdminPayHistory.tsx
src/types/adminPayHistory.ts

- close #110 
- 코인일 경우 type을 '코인', 패스일 경우 type '패스'로 get 요청
- 검색도 쿼리에 넣어 요청
- 페이지네이션 구현
화면 스크롤은 모두 머지 후 한 번에 수정해야 할 것 같습니다.
검색 유형 드롭다운을 추후 추가할 예정입니다.

[Feature] 어드민 구매 내역 api 연결

---

src/pages/admin/AdminFitnessUpload/AdminFitnessUpload.tsx
src/pages/admin/AdminFitnessUpload/SetLocationModal.tsx
src/routes/Router.tsx

- close #87 
- 주소 검색 및 설정 모달 구현
- 로컬스토리지에 주소, 위도, 경도를 저장해두었습니다. api 요청 시 사용해주세요!

[Feature] 어드민 시설 등록의 주소 검색 및 설정 모달 구현

---

src/apis/adminManagement/adminSubscribe.ts
src/components/adminCommon/ManagementInput.tsx
src/hooks/useGetAdminSubsribe.ts
src/pages/admin/AdminSubscribe.tsx
src/types/adminSubsribe.ts

- close #126 
- 구독 상품 목록 데이터 get 요청으로 표시
- 데이터 수정 후 put 요청으로 데이터 변경

[Feature] 어드민 구독 상품 관리 API 연결

---

src/apis/adminManagement/adminCoint.ts
src/hooks/useGetAdminCoins.ts
src/pages/admin/AdminCoin.tsx
src/pages/admin/AdminSubscribe.tsx
src/types/adminCoint.ts

- close #128 
- 코인 상품 목록 데이터 get 요청으로 표시
- 데이터 수정 후 put 요청으로 데이터 변경

[Feature] 어드민 코인 상품 관리 api 연결

---

src/pages/Signin/InputField.tsx
src/pages/admin/AdminDashboard.tsx
src/pages/admin/AdminUser.tsx

- close #130 
- 공통 페이지네이션 사용
- 어드민 api 연결 시 로딩, 에러 처리

[Refact] admin 페이지

---

src/pages/MyPage/MyProfile.tsx
src/pages/admin/AdminNotice.tsx

- close #143 
- 이전 pr에서 반영한 페이지네이션이 admin/notice에서 수정이 안되어 있어 다시 올립니다.

[Feature] 페이지네이션 부분 수정

---

src/apis/UpdateReview/axios/updateReviewApi.ts
src/apis/UpdateReview/quries/useUpdateReviewApi.ts
src/apis/adminNotice/quries/useAdminNoticeApi.ts
src/apis/adminNotice/quries/useAdminNoticeUploadApi.ts
src/components/Header.tsx
src/pages/FitnessDetails/ReviewItem.tsx
src/pages/MyPage/LogoutModal.tsx
src/pages/UpdateReview.tsx
src/pages/UploadReview.tsx
src/pages/UsePass/AvailableList.tsx
src/pages/admin/AdminNotice.tsx
src/pages/admin/AdminNoticeUpload.tsx
src/pages/index.ts
src/routes/Router.tsx

- close #149 
- 리뷰 수정하기 퍼블리싱, api

[Feature] 리뷰 수정하기 퍼블리싱, api

---

src/pages/FitnessDetails/FitnessDetails.tsx
src/pages/FitnessDetails/ReviewList.tsx
src/pages/Home/Home.tsx

- 미로그인 시 리뷰에 '로그인 후 리뷰 확인이 가능합니다.' 표시
- 미로그인 시 패스 구매하기 버튼 비활성화

[Deploy] 미로그인 시 UI 처리 수정

---

src/apis/signup/signup.ts
src/context/AuthContext.tsx
src/hooks/useSignin.ts
src/pages/Home/Home.tsx
src/pages/MyPage/MyPage.tsx
src/pages/Signup/SignupStep2.tsx

- 회원가입 시 위치 약관 미동의면 모달 띄우기
- 로그인 시 위치 미동의면 모달 띄우기
- 로그아웃 전역 관리

위치 약관 미동의 시 모달 구현

---

index.html

- close #169
- 기본 메타 태그 등록
- SNS 공유 최적화 (Open Graph) 메타 태그 등록
- Twitter Card (트위터 카드) 메타 태그 등록

[Feat] 메타 태그 추가

---

src/components/Navbar.tsx
src/pages/Notice/Notice.tsx
src/pages/index.ts
src/pages/owner/dashboard/OwnerDashboard.tsx
src/pages/owner/history/SettlementHistory.tsx
src/pages/owner/history/UsageHistory.tsx
src/pages/owner/notice/NoticeDetails.tsx
src/pages/owner/notice/Notices.tsx

- close #168 
- 사장님 대시보드 UI 구현
- 정산, 이용 내역 UI 구현
- 공지사항 UI 구현
스크린샷 보시다싶이 내용물 ui 구현은 했지만 위아래 pathname, navbar 영역 수정 필요한 상태입니다!

[Feat] 사장님 화면 ui

---

src/apis/owner/dashboard.ts
src/apis/owner/history.ts
src/hooks/useGetOwnerDashboardQueries.ts
src/hooks/useGetOwnerHistory.ts
src/pages/owner/dashboard/OwnerDashboard.tsx
src/pages/owner/history/SettlementHistory.tsx

- close #182 
- 사장님 대시보드 화면에서 시설 없을때 '등록된 업체가 없습니다.' 처리

feat: 사장님 대시보드 시설 없을때 처리

---

src/index.css
src/pages/ExploreFitness/ExploreFitness.tsx
src/pages/Home/Home.tsx
src/pages/MyPage/MyPage.tsx
src/pages/MyPage/SectionComponent.tsx

- close #190
- 홈 화면 슬라이더 오류 해결
- 홈 전체 height가 화면크기에 맞지 않는 오류 해결
- 마이페이지의 y-scroll이 생기지 않는 오류 해결

[Style] 고객 페이지 스타일 오류 수정

---

src/components/subscribe/PlanInfo.tsx
src/pages/BuyCoins.tsx
src/pages/MyPage/MyPage.tsx
src/types/payment.ts

- close #133
- 구독 요금제 api 연동
- 코인 안내 api 연동
- min-h 문제 해결
스타일 깨지는지 확인해주세요!

[Feature] 구독 및 코인 요금제 안내 api 연동

---

src/apis/adminNotice/axios/adminNoticeAPI.ts
src/apis/adminNotice/axios/adminNoticeUploadApi.ts
src/apis/adminNotice/quries/useAdminNoticeApi.ts
src/apis/adminNotice/quries/useAdminNoticeUploadApi.ts
src/pages/admin/AdminNotice.tsx
src/pages/admin/AdminNoticeUpload.tsx
src/routes/adminRoutes.tsx

- close #196 
- 공지사항 회원/시설 슬라이드 게시 체크박스 수정
- 공지사항 작성 화면 회원/시설 타입 추가
- 공지사항 수정 api 연결
고려사항이 많아서... 일단 임시저장 상태인 글은 수정 못하게 막아뒀습니다
공지사항 삭제하지 못하는게 불편하네요...ㅎㅎ

[Feat] 어드민 공지사항 수정

---

src/components/payment/SelectPayOption.tsx
src/pages/Payment.tsx

- close #203 
- 등록된 카드 선택 시 선택된 카드의 형식을 지정하여 오류를 해결했습니다.
해당 브랜치에서 코인 구매가 잘 되는지 확인 부탁드립니다! (카드 미등록의 경우 카드 등록 먼저 부탁드려요)

[Fix] 등록된 카드로 코인 구매 시 발생한 오류 해결

---

src/apis/mypage/axios/profileApi.ts
src/apis/mypage/quries/useProfileApi.ts
src/apis/usepass/axios/usepassApi.ts
src/hooks/useSignin.ts
src/pages/MyPage/MyPage.tsx

- close #207 
- 마이페이지, 보유 패스 화면에서 프로필 조회 오류 콘솔 제거
- 불필요한 콘솔 제거

[Fix] 비로그인 상태에서 프로필 조회 api 연결시 오류 출력 제거

---

src/apis/adminUser/adminFitnessUser.ts
src/hooks/useGetAdminUser.ts
src/layout/RootStyleManager.tsx
src/pages/admin/user/AdminFitnessRequest.tsx

- close #211 
- 시설 승인 요청 화면에서 상태가 '승인 대기'인 시설들만 보이게 수정
- 어드민으로 로그인하면 레이아웃 이상하게 보이는 문제 수정

[Fix] 어드민 시설 승인 요청 화면 수정

---

src/apis/adminFitness/adminFitnessData.ts
src/apis/signup/social-login.ts
src/components/Modal.tsx
src/hooks/useSocialSignup.ts
src/pages/Signup/SignupStep2.tsx
src/pages/admin/AdminFitnessList/AdminFitnessList.tsx
src/pages/admin/AdminFitnessList/FitnessRowDropdown.tsx
src/pages/owner/signup/Step3.tsx

- close #220 
- 시설 목록 드롭다운 (삭제, 수정, 구매 상태 변경 기능)

[Feat] 어드민 시설 목록 드롭다운 구현
